package analysis

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGitIntegration_IsGitRepository(t *testing.T) {
	// Test with non-git directory
	tmpDir := t.TempDir()
	git := NewGitIntegration(tmpDir)

	if git.IsGitRepository() {
		t.Error("Expected false for non-git directory")
	}

	// Test with git directory (create .git directory)
	gitDir := filepath.Join(tmpDir, ".git")
	if err := os.Mkdir(gitDir, 0755); err != nil {
		t.Fatalf("Failed to create .git directory: %v", err)
	}

	if !git.IsGitRepository() {
		t.Error("Expected true for git directory")
	}
}

func TestGitIntegration_GetAllGoFiles(t *testing.T) {
	tmpDir := t.TempDir()
	git := NewGitIntegration(tmpDir)

	// Create test files
	files := []string{
		"main.go",
		"utils.go",
		"main_test.go",  // Should be excluded
		"utils_test.go", // Should be excluded
		"subdir/module.go",
		"subdir/module_test.go",     // Should be excluded
		"vendor/external.go",        // Should be excluded
		"testdata/fixture.go",       // Should be excluded
		"subdir/testdata/nested.go", // Should be excluded (nested testdata)
		".hidden/file.go",           // Should be excluded
		"README.md",                 // Should be excluded
	}

	for _, file := range files {
		filePath := filepath.Join(tmpDir, file)
		dir := filepath.Dir(filePath)

		if err := os.MkdirAll(dir, 0755); err != nil {
			t.Fatalf("Failed to create directory %s: %v", dir, err)
		}

		if err := os.WriteFile(filePath, []byte("package main"), 0600); err != nil {
			t.Fatalf("Failed to create file %s: %v", file, err)
		}
	}

	goFiles, err := git.GetAllGoFiles()
	if err != nil {
		t.Fatalf("Failed to get Go files: %v", err)
	}

	// Should only include non-test Go files
	expected := []string{
		filepath.Join(tmpDir, "main.go"),
		filepath.Join(tmpDir, "utils.go"),
		filepath.Join(tmpDir, "subdir", "module.go"),
	}

	if len(goFiles) != len(expected) {
		t.Errorf("Expected %d Go files, got %d", len(expected), len(goFiles))
	}

	// Check that all expected files are present
	fileSet := make(map[string]bool)
	for _, file := range goFiles {
		fileSet[file] = true
	}

	for _, expectedFile := range expected {
		if !fileSet[expectedFile] {
			t.Errorf("Expected file %s not found in results", expectedFile)
		}
	}
}

func TestGitIntegration_GetAllGoFiles_GeneratedFiles(t *testing.T) {
	tmpDir := t.TempDir()

	os.WriteFile(filepath.Join(tmpDir, "main.go"), []byte("package main"), 0644)
	os.WriteFile(filepath.Join(tmpDir, "client.go"), []byte(`// Code generated by example-generator. DO NOT EDIT.

package main
`), 0644)
	// A filename pattern alone must not exclude a file.
	os.WriteFile(filepath.Join(tmpDir, "foo_generated.go"), []byte("package main"), 0644)

	t.Run("excludes generated file by default", func(t *testing.T) {
		git := NewGitIntegration(tmpDir)

		files, err := git.GetAllGoFiles()
		if err != nil {
			t.Fatalf("Failed to get Go files: %v", err)
		}

		for _, f := range files {
			if strings.HasSuffix(f, "client.go") {
				t.Errorf("expected client.go to be excluded, got files: %v", files)
			}
		}

		if len(files) != 2 {
			t.Errorf("expected 2 files, got %d: %v", len(files), files)
		}
	})

	t.Run("includes generated file when SetIncludeGenerated(true)", func(t *testing.T) {
		git := NewGitIntegration(tmpDir)
		git.SetIncludeGenerated(true)

		files, err := git.GetAllGoFiles()
		if err != nil {
			t.Fatalf("Failed to get Go files: %v", err)
		}

		found := false

		for _, f := range files {
			if strings.HasSuffix(f, "client.go") {
				found = true
			}
		}

		if !found {
			t.Errorf("expected client.go to be included, got files: %v", files)
		}

		if len(files) != 3 {
			t.Errorf("expected 3 files, got %d: %v", len(files), files)
		}
	})
}

// newTestGitRunner returns a helper that runs git commands against dir.
func newTestGitRunner(t *testing.T, dir string) func(args ...string) {
	t.Helper()

	return func(args ...string) {
		t.Helper()

		cmd := exec.Command("git", args...)
		cmd.Dir = dir

		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}
}

// commitFiles writes the given files under dir and commits them.
func commitFiles(t *testing.T, dir string, runGit func(args ...string), files map[string]string) {
	t.Helper()

	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
		}

		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
	}

	runGit("add", ".")
	runGit("commit", "-m", "commit")
}

func TestGitIntegration_GetChangedFiles_GeneratedFiles(t *testing.T) {
	tmpDir := t.TempDir()
	runGit := newTestGitRunner(t, tmpDir)

	runGit("init", "-b", "main")
	// Repo-local identity so the test does not depend on (or mutate) the
	// machine's global git config.
	runGit("config", "user.email", "test@example.com")
	runGit("config", "user.name", "Test")

	commitFiles(t, tmpDir, runGit, map[string]string{
		"go.mod":  "module example\n\ngo 1.24\n",
		"main.go": "package main\n",
	})

	// Add the new files on a feature branch, mirroring a PR's changes
	// relative to main.
	runGit("checkout", "-b", "feature")
	commitFiles(t, tmpDir, runGit, map[string]string{
		"util.go": "package main\n",
		"client.go": `// Code generated by example-generator. DO NOT EDIT.

package main
`,
	})

	t.Run("excludes generated file by default", func(t *testing.T) {
		git := NewGitIntegration(tmpDir)

		files, err := git.GetChangedFiles("main")
		if err != nil {
			t.Fatalf("GetChangedFiles: %v", err)
		}

		for _, f := range files {
			if strings.HasSuffix(f, "client.go") {
				t.Errorf("expected client.go to be excluded, got files: %v", files)
			}
		}
	})

	t.Run("includes generated file when SetIncludeGenerated(true)", func(t *testing.T) {
		git := NewGitIntegration(tmpDir)
		git.SetIncludeGenerated(true)

		files, err := git.GetChangedFiles("main")
		if err != nil {
			t.Fatalf("GetChangedFiles: %v", err)
		}

		found := false

		for _, f := range files {
			if strings.HasSuffix(f, "client.go") {
				found = true
			}
		}

		if !found {
			t.Errorf("expected client.go to be included, got files: %v", files)
		}
	})
}

func TestGitIntegration_GetChangedFiles_NotGitRepo(t *testing.T) {
	tmpDir := t.TempDir()
	git := NewGitIntegration(tmpDir)

	_, err := git.GetChangedFiles("main")
	if err == nil {
		t.Error("Expected error for non-git repository")
	}
}

func TestGitIntegration_GetCurrentBranch_NotGitRepo(t *testing.T) {
	tmpDir := t.TempDir()
	git := NewGitIntegration(tmpDir)

	_, err := git.GetCurrentBranch()
	if err == nil {
		t.Error("Expected error for non-git repository")
	}
}

func TestGitIntegration_HasUncommittedChanges_NotGitRepo(t *testing.T) {
	tmpDir := t.TempDir()
	git := NewGitIntegration(tmpDir)

	_, err := git.HasUncommittedChanges()
	if err == nil {
		t.Error("Expected error for non-git repository")
	}
}
