package analysis

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsExcludedPath(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		path string
		want bool
	}{
		{
			name: "vendor directory",
			path: "vendor/external.go",
			want: true,
		},
		{
			name: "testdata directory",
			path: "testdata/fixture.go",
			want: true,
		},
		{
			name: "nested testdata directory",
			path: "internal/execution/testdata/arithmetic.go",
			want: true,
		},
		{
			name: "nested vendor directory",
			path: "internal/vendor/pkg/lib.go",
			want: true,
		},
		{
			name: "vendor as exact directory segment",
			path: "vendor",
			want: true,
		},
		{
			name: "regular source file",
			path: "internal/mutation/engine.go",
			want: false,
		},
		{
			name: "substring vendor is not excluded",
			path: "internal/myvendor/lib.go",
			want: false,
		},
		{
			name: "substring testdata is not excluded",
			path: "internal/testdatautil/helper.go",
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			if got := IsExcludedPath(tt.path); got != tt.want {
				t.Errorf("IsExcludedPath(%q) = %v, want %v", tt.path, got, tt.want)
			}
		})
	}
}

func TestIsGeneratedFile(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		file    string
		content string
		want    bool
	}{
		{
			name: "standard marker excludes regardless of filename",
			file: "client.go",
			content: `// Code generated by example-generator. DO NOT EDIT.

package example

func Add(a, b int) int {
	return a + b
}
`,
			want: true,
		},
		{
			name: "ordinary source file remains eligible",
			file: "client.go",
			content: `package example

func Add(a, b int) int {
	return a + b
}
`,
			want: false,
		},
		{
			name: "filename alone does not mark a file as generated",
			file: "foo_generated.go",
			content: `package example

func Add(a, b int) int {
	return a + b
}
`,
			want: false,
		},
		{
			name:    "unparseable file is treated as not generated",
			file:    "broken.go",
			content: `not valid go code!`,
			want:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			dir := t.TempDir()
			path := filepath.Join(dir, tt.file)

			if err := os.WriteFile(path, []byte(tt.content), 0o600); err != nil {
				t.Fatalf("write %s: %v", path, err)
			}

			if got := IsGeneratedFile(path); got != tt.want {
				t.Errorf("IsGeneratedFile(%q) = %v, want %v", path, got, tt.want)
			}
		})
	}

	t.Run("non-existent file is treated as not generated", func(t *testing.T) {
		t.Parallel()

		if got := IsGeneratedFile(filepath.Join(t.TempDir(), "missing.go")); got {
			t.Error("expected non-existent file to not be reported as generated")
		}
	})
}
