name: CI
on:
  pull_request:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sivchari/actions-kit@main
        with:
          skip-goreleaser-check: true

