name: Mutation Testing

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for incremental analysis
    
    - name: Build gomu binary
      run: go build -o gomu ./cmd/gomu
    
    - name: Add gomu to PATH
      run: echo "$PWD" >> $GITHUB_PATH
    
    - name: Run mutation testing with gomu action
      uses: ./  # Use the local action.yaml for self-validation
      with:
        go-version: '1.24'
        upload-artifacts: 'true'
        comment-pr: 'true'
        version: 'local'
        workers: '2'
        timeout: '10'
