name: Mutation Testing

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for incremental analysis
    
    - name: Run mutation testing with gomu action
      uses: ./  # Use the local action.yaml for self-validation
      with:
        go-version: '1.24'
        config-file: '.gomu.yaml'
        upload-artifacts: 'true'
        comment-pr: 'true'
